homeassistant:
  customize: !include yamls/customize.yaml
  packages: !include_dir_named packages
  
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

# yamls

automation: !include automations.yaml
camera: !include yamls/camera.yaml
group: !include yamls/groups.yaml
#home_modes: !include yamls/home_modes.yaml
scene: !include yamls/scenes.yaml
script: !include yamls/scripts.yaml
sensor: !include yamls/sensor.yaml

sensor places_steve:
  - platform: places
    name: steve
    devicetracker_id: device_tracker.mi_a2_lite
    options: zone,place
    map_provider: google
    map_zoom: 19
    home_zone: zone.home
    api_key: !secret email_steve

    



mqtt:
  discovery: true
  broker: mqtt://192.168.0.119:1883
 # birth_message and will_message is not required anymore for Home Assistant 0.113 >=
 # birth_message:
 #   topic: 'hass/status'
 #  payload: 'online'
 # will_message:
 #   topic: 'hass/status'
  #  payload: 'offline'


esphome:
