homeassistant:
  customize: !include yamls/customize.yaml
 # packages: !include_dir_named packages
  
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

# Yamls
# Example configuration.yaml entry

automation: !include automations.yaml
camera: !include yamls/camera.yaml
group: !include yamls/groups.yaml
#home_modes: !include yamls/home_modes.yaml
script: !include scripts.yaml
#sensor: !include yamls/sensor.yaml
sensor: !include_dir_merge_list sensors/
scene: !include scenes.yaml
#binary_sensor: !include /yamls/binary_sensor.yaml
binary_sensor: !include_dir_merge_list binary_sensors/

 
mqtt:
  discovery: true
  broker: mqtt://192.168.0.119:1883
 # birth_message and will_message is not required anymore for Home Assistant 0.113 >=
 # birth_message:
 #   topic: 'hass/status'
 #  payload: 'online'
 # will_message:
 #   topic: 'hass/status'
  #  payload: 'offline'

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: '1234'
    arming_time: 15
    delay_time: 30
    trigger_time: 15
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0
    
esphome:

