################################################
### REST Sensor Quote of the Day OOTD ##########
################################################

- platform: rest
  resource: https://quotes.rest/qod?language=en
  name: Quote of the Day
  scan_interval: 43200
  json_attributes_path: '$.contents.quotes[0]'
  json_attributes:
    - quote
    - author
    - category
  value_template: 'OK'