- platform: template
    sensors:
      nextsunrise:
        entity_id: sun.sun
        friendly_name: 'Next Sunrise'
        icon_template: mdi:weather-sunset-up
        unit_of_measurement: ' '
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%H.%M') }}
      nextsunset:
        entity_id: sun.sun
        friendly_name: 'Next Sunset'
        icon_template: mdi:weather-sunset-down
        unit_of_measurement: ' '
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%H.%M') }}
  