- platform: mqtt
  device_class: motion
  state_topic: "selfmon/vmod/prio/inputs/read/1001"
  name: "Kitchen selfmon"
  off_delay: 2
  payload_on: "OPEN"
  payload_off: "CLOSED"
  
- platform: mqtt
  device_class: motion
  state_topic: "selfmon/vmod/prio/inputs/read/1002"
  name: "Dining room selfmon"
  off_delay: 2
  payload_on: "OPEN"
  payload_off: "CLOSED"

  
- platform: mqtt
  device_class: motion
  state_topic: "selfmon/vmod/prio/inputs/read/1003"
  name: "Living Room selfmon"
  off_delay: 2
  payload_on: "OPEN"
  payload_off: "CLOSED"
  
- platform: mqtt
  device_class: motion
  state_topic: "selfmon/vmod/prio/inputs/read/1004"
  name: "Upstairs selfmon"
  off_delay: 2
  payload_on: "OPEN"
  payload_off: "CLOSED"
  
- platform: mqtt
  device_class: motion
  state_topic: "selfmon/vmod/prio/inputs/read/1011"
  name: "Hall selfmon"
  off_delay: 2
  payload_on: "OPEN"
  payload_off: "CLOSED"
  
- platform: mqtt
  device_class: door
  state_topic: "selfmon/vmod/prio/inputs/read/1012"
  name: "Shed Door selfmon"
  payload_on: "OPEN"
  payload_off: "CLOSED"
  
- platform: mqtt
  device_class: door
  state_topic: "selfmon/vmod/prio/inputs/read/1013"
  name: "Back Door selfmon"
  payload_on: "OPEN"
  payload_off: "CLOSED"
  
- platform: mqtt
  device_class: door
  state_topic: "selfmon/vmod/prio/inputs/read/1014"
  name: "Front Door selfmon"
  payload_on: "OPEN"
  payload_off: "CLOSED"
  
- platform: mqtt
  device_class: motion
  state_topic: "selfmon/vmod/prio/inputs/read/1021"
  name: "Shed Pir selfmon"
  off_delay: 2
  payload_on: "OPEN"
  payload_off: "CLOSED"
